version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch

volumes:
  esdata:
    driver: local
